import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        Headers: 'readonly',
        navigator: 'readonly',
        fetch: 'readonly',
        FormData: 'readonly',
        Blob: 'readonly',
        Audio: 'readonly',
        URL: 'readonly',
        MediaRecorder: 'readonly',
        AudioContext: 'readonly',
        OfflineAudioContext: 'readonly',
        DataView: 'readonly',
        ArrayBuffer: 'readonly',
        Float32Array: 'readonly',
        Float64Array: 'readonly',
        Uint8Array: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Promise: 'readonly',
        Infinity: 'readonly',
        speechSynthesis: 'readonly',
        SpeechSynthesisUtterance: 'readonly',
        localStorage: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    },
  },
];
